#!/bin/bash

if ! command -v 7z
then
	echo "Installing p7zip-rar..."
	sudo apt install -y p7zip-rar >> p7zip_rar_install.log
	printf "\x1b[33mInstallation complete\x1b[0m\n"
	echo "Installation log created: ./p7zip_rar_install.log"
fi

if [ $1 = a ]
then
	7z a -t7z $2.7z $2
elif [ $1 = e ]
then
	7z e $2 -o$3
else
	echo "invalid arguments"
	exit 1
fi
