#!/bin/bash

# Color definitions

reset="\x1b[0m"
green="\x1b[38;5;47m"
red="\x1b[38;5;196m"
blue="\x1b[38;5;27m"
yellow="\x1b[38;5;220m"

# log files
suclog=/var/log/archive_script.log
errlog=/var/log/archive_script_err.log

# function to check exit code
check_exit_code(){
  if [ $? -ne 0 ]
  then
    echo "An error occurred, (exit code: $?). Check $errlog for more details"
  fi
}

# function to check for 7z command
check_7z(){
	if ! command -v 7z
	then
		echo "installing p7zip-rar..."
		sudo apt install p7zip-rar >>$suclog 2>>$errlog
		check_exit_code
	fi
}

printf "\t"$green"Menu-based archive script"$reset"\n"
